name: Checking AS02 Build 

on:
  push:
    branches:
      - main

jobs:
  check-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 19
      uses: actions/setup-java@v4
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
        
    - name: Check number of branches
      run: |
        git fetch --all
        git branch -r | grep -v main | wc -l
        # Check for non-main branches

    - name: Check commit history
      run: |
        git log --oneline | wc -l
        # Check number of commits
    
    # Check CI/CD validation
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Validate CI workflow file
      run: |
        if [ -f ".github/workflows/CICD.yml" ]; then
         echo "CI pipeline file found."
        else
          echo "CI pipeline file is missing."
          exit 1
        fi

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run tests with Maven
      run: mvn test

    - name: Set up SonarCloud
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        sonar-token: ${{ secrets.SONAR_TOKEN }} # You must add this secret to GitHub Settings

    - name: Run SonarCloud Analysis
      run: mvn sonar:sonar -Dsonar.projectKey=your-sonarcloud-project-key -Dsonar.organization=your-sonarcloud-organization
      
        # App running
    - name: Build Docker image
      run: |
       docker build -t musicfinder .
       docker run -d -p 8080:8080 musicfinder &
       sleep 10

    - name: Check if app is running on port 8080
      run: |
        curl -X GET "http://localhost:8080/artist/Adele" -H "Accept: application/json"
